name: Build 

on: 
  push:
    branches:
      - master

Jobs:
  build: 
    runs-on: ubuntu-lastest 
    strategy:
    matrix:
      python-versions : [ "3.9" , "3.10" ]

    steps:
    - name: Check your repo
    - uses: actions/checkout@v4

    - name: to set up python ${{ matrix.python-versions }}
    - uses: actions/python@v3
     with:
       python-versions : ${{ matrix.python-versions }}

    - name: to install dependencies
    - run: | 
      python -m pip install --upgrade pip 
      pip install pylint 

    - name: To check python code in repos  
    - run: |
      pylint $(git ls-files '*.py')
       

      
      
    
    
    


