name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Fixed typo in 'ubuntu-latest'
    
    strategy:
      matrix:
        python-versions: ["3.9", "3.10"]  # Fixed indentation and array syntax

    steps:
    - name: Check out repository
      uses: actions/checkout@v4  # Fixed action version to 'v4'

    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v2  # Fixed action name to 'setup-python'
      with:
        python-version: ${{ matrix.python-versions }}  # Fixed to 'python-version'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Check Python code in repository
      run: |
        pylint $(git ls-files '*.py')
